library(rmarkdown)

render("Preliminaries.Rmd",output_format="all")
render("Chapter3.Rmd",output_format="all")
render("Chapter4.Rmd",output_format="all")
render("Chapter5.Rmd",output_format="all")
render("Chapter6.Rmd",output_format="all")
render("Chapter7.Rmd",output_format="all")
render("Chapter8.Rmd",output_format="all")
render("Chapter9.Rmd",output_format="all")
render("Chapter10.Rmd",output_format="all")
render("Chapter11.Rmd",output_format="all")
render("Chapter12.Rmd",output_format="all")
render("Chapter13.Rmd",output_format="all")
render("Chapter15.Rmd",output_format="all")
