---
title: "AIFFD Chapter 12 - Bioenergetics"
author: "Derek H. Ogle"
csl: american-fisheries-society.csl
output:
  pdf_document:
    fig_height: 3
    fig_width: 3
    number_sections: yes
    pandoc_args: --number-offset=12
    toc: yes
    toc_depth: 2
  html_document:
    fig_height: 4.5
    fig_width: 4.5
    highlight: tango
    number_sections: yes
    pandoc_args: --number-offset=12
    toc: yes
    toc_depth: 2
bibliography: AIFFDReferences.bib
---
\setcounter{section}{12}

```{r echo=FALSE, include=FALSE}
stime <- proc.time()    # Start time to get processing time
source('knitr_setup.R')
```

--------------------------------------------------------------

This document contains R versions of the boxed examples from **Chapter 12** of the "Analysis and Interpretation of Freshwater Fisheries Data" book.  Some sections build on descriptions from previous sections, so each section may not stand completely on its own.  More thorough discussions of the following items are available in linked vignettes:

* the use of linear models in R in the [preliminaries vignette](https://fishr.wordpress.com/books/aiffd/),
* differences between and the use of type-I, II, and III sums-of-squares in the [preliminaries vignette](https://fishr.wordpress.com/books/aiffd/), and
* the use of "least-squares means" is found in the [preliminaries vignette](https://fishr.wordpress.com/books/aiffd/).

The following additional packages are required to complete all of the examples (with the required functions noted as a comment and also noted in the specific examples below).

```{r echo=-1, warning=FALSE, message=FALSE}
rqrd <- c("FSA","car","plyr")
library(FSA)          # Subset, Summarize, residPlot
library(car)          # Anova, recode
library(plyr)         # ddply
```

In addition, external tab-delimited text files are used to hold the data required for each example.  These data are loaded into R in each example with `read.table()`.  Before using `read.table()` the working directory of R must be set to where these files are located on **your** computer.  The working directory for all data files on **my** computer is set with

```{r}
setwd("C:/aaaWork/Web/fishR/BookVignettes/aiffd2007")
```

In addition, I prefer to not show significance stars for hypothesis test output, reduce the margins on plots, alter the axis label positions, and reduce the axis tick length.  In addition, contrasts are set in such a manner as to force R output to match SAS output for linear model summaries.  All of these options are set with
```{r eval=FALSE}
options(width=90,continue=" ",show.signif.stars=FALSE,
        contrasts=c("contr.sum","contr.poly"))
par(mar=c(3.5,3.5,1,1),mgp=c(2.1,0.4,0),tcl=-0.2)
```


## Scope for Growth
**THERE IS NO CODE TO CONVERT FOR THIS BOX**


## Sample Analysis of Striped Bass Data
Presented here is a step-by-step account of an approach to analyzing common energetic data such as $C_{max}$ or metabolism.  In the example provided here, data are from maximum consumption experiments for Striped Bass (*Morone saxatilis*) conducted by @Hartman1993.  The data set (available in the Chapter 12 compact disc (CD) folder) is arranged by the variables wet weight, temperature, and ration.

### Preparing Data
The [Box12_2.txt data file](https://raw.githubusercontent.com/droglenc/aiffd2007/master/data/Box12_2.txt) is read and the structure of the data frame is observed below.
```{r}
d2 <- read.table("data/Box12_2.txt",header=TRUE)
str(d2)
```

In addition, I created a new variable, called `tempA`, that contains the temperature groupings used to construct Figure A in the box.  The temperature groupings were identified by examining the Excel file provided on the companion CD.
```{r}
d2$tempA <- NA
d2$tempA[d2$temp>6 & d2$temp<9] <- 6.9
d2$tempA[d2$temp>21 & d2$temp<24] <- 22.4
d2$tempA[d2$temp>28 & d2$temp<31] <- 29.6
d2$tempA <- factor(d2$tempA)
str(d2)
```

Another new variable, called `wtA`, was created to contain the size groupings used to construct Figure B in the box.  The cutoff values were as stated in the caption for Figure B.
```{r}
d2$wtA <- NA
d2$wtA[d2$wt<77] <- 38
d2$wtA[d2$wt>130 & d2$wt<730] <- 403
d2$wtA[d2$wt>800] <- 1567
d2$wtA <- factor(d2$wtA)
str(d2)
```

### Plots
The authors fit a power function to the maximum consumption versus weight variables for the 22.4 and 29.6 degrees grouping and a linear function to the 6.9 degrees group.  The power functions are fit as linear models on the log-log data.  The code below first transforms the maximum consumption and weight variables to the common log scale.  The linear model for the 6.9 group is then fit with `lm()` using a formula of the form `response`~`explanatory`, submitting the data file containing the variables in the `data=` argument, and then using the `subset=` argument to isolate the 6.9 group.  The model coefficients are extracted from the saved `lm` object with `coef()`.  Linear models are fit to the log-log data for the other two groups.
```{r}
d2$logwt <- log10(d2$wt)
d2$logCmax <- log10(d2$Cmax)
lm.low <- lm(Cmax~wt,data=d2,subset=tempA=="6.9")
coef(lm.low)
lm.med <- lm(logCmax~logwt,data=d2,subset=tempA=="22.4")
coef(lm.med)
lm.hi  <- lm(logCmax~logwt,data=d2,subset=tempA=="29.6")
coef(lm.hi)
```

Figure A is constructed in parts by first making a raw schematic plot (note that `type="n"` will result in no points or lines being plotted), then adding points for each grouping, and then adding the curves derived from the coefficients for each grouping.
```{r}
# schematic plot
plot(Cmax~wt,data=d2,type="n",xlab="Wet weight (g)",ylab="Cmax(g/g/d)")
# add points specific to each group
points(Cmax~wt,data=d2,subset=tempA=="6.9",pch=19,col="red")
points(Cmax~wt,data=d2,subset=tempA=="22.4",pch=19,col="blue")
points(Cmax~wt,data=d2,subset=tempA=="29.6",pch=19,col="black")
# add the fitted curve specific to each group
curve(coef(lm.low)[1]+coef(lm.low)[2]*x,min(d2$wt[d2$tempA=="6.9"],na.rm=TRUE),
      max(d2$wt[d2$tempA=="6.9"],na.rm=TRUE),add=TRUE,col="red",lwd=2)
curve(10^(coef(lm.med)[1])*x^coef(lm.med)[2],min(d2$wt[d2$tempA=="22.4"],na.rm=TRUE),
      max(d2$wt[d2$tempA=="22.4"],na.rm=TRUE),add=TRUE,col="blue",lwd=2)
curve(10^(coef(lm.hi)[1])*x^coef(lm.hi)[2],min(d2$wt[d2$tempA=="29.6"],na.rm=TRUE),
      max(d2$wt[d2$tempA=="29.6"],na.rm=TRUE),add=TRUE,col="black",lwd=2)
# add a legend
legend("topright",legend=c("6.9C","22.4C","29.6C"),pch=19,col=c("red","blue","black"),
       lty=1,lwd=2)
```

The polynomial regressions for the relationship between maximum consumption and temperature shown in Figure B are also fit with `lm()` using a formula that represents the quadratic function.  Note in the formula that `I()` must be wrapped around the quadratic term so that R will know to actually square that term (i.e., the `\^2` notation has a special meaning in the model formula if not contained within `I()`).  Figure B is then constructed in parts as described for Figure A.
```{r}
lm.sm <- lm(Cmax~temp+I(temp^2),data=d2,subset=wtA=="38")
coef(lm.sm)
lm.int <- lm(Cmax~temp+I(temp^2),data=d2,subset=wtA=="403")
coef(lm.int)
lm.lrg  <- lm(Cmax~temp+I(temp^2),data=d2,subset=wtA=="1567")
coef(lm.lrg)

# The plot
plot(Cmax~temp,data=d2,type="n",xlab="Temperature (C)",ylab="Cmax(g/g/d)")
points(Cmax~temp,data=d2,subset=wtA=="38",pch=19,col="red")
points(Cmax~temp,data=d2,subset=wtA=="403",pch=19,col="blue")
points(Cmax~temp,data=d2,subset=wtA=="1567",pch=19,col="black")
curve(coef(lm.sm)[1]+coef(lm.sm)[2]*x+coef(lm.sm)[3]*x^2,min(d2$temp,na.rm=TRUE),
      max(d2$temp,na.rm=TRUE),add=TRUE,col="red",lwd=2)
curve(coef(lm.int)[1]+coef(lm.int)[2]*x+coef(lm.int)[3]*x^2,min(d2$temp,na.rm=TRUE),
      max(d2$temp,na.rm=TRUE),add=TRUE,col="blue",lwd=2)
curve(coef(lm.lrg)[1]+coef(lm.lrg)[2]*x+coef(lm.lrg)[3]*x^2,min(d2$temp,na.rm=TRUE),
      max(d2$temp,na.rm=TRUE),add=TRUE,col="black",lwd=2)
legend("topleft",legend=c("38 g","403 g","1567 g"),pch=19,col=c("red","blue","black"),
       lty=1,lwd=2)
```

### Test for Significant Interaction Terms
The authors then begin to test for a significant interaction effect of weight and temperature on maximum consumption.  Before doing this analysis the authors removed all observations where maximum consumption was equal to zero.  This filtering is accomplished with `Subset()`, from the `FSA` package.  This function requires the orginal data frame as the first argument and the conditioning statement as the second argument.
```{r}
d2a <- Subset(d2,Cmax>0)
```

The linear model is then fit with `lm()` using a formula of the form `response`~`explanatory1*explanatory2`.  This formula is a short-hand method to tell R to fit the two main effects and the interaction effect of the two explanatory variables on the right-hand-side of the formula.  The type-I ANOVA table is extracted by submitting the saved `lm` object to `anova()` and the Type-III ANOVA table is extracted by submitting the saved `lm` object to `Anova()` with the `type="III"` argument.  As the authors' noted, the interation term is not siginificant if a 5% significance level is used.
```{r}
lm1 <- lm(logCmax~logwt*temp,data=d2a)
anova(lm1)
Anova(lm1,type="III")
```

### Developing a Statistical Model
The authors then developed a multiple linear regression model to describe maximum consumption based on the logarithm of weight and linear and quadratic temperature terms.  This model is again fit with `lm()`, the ANOVA table is extracted as described above, and the model coefficients are extracted from the `lm` object with `summary()`.
```{r}
lm2 <- lm(logCmax~logwt+temp+I(temp^2),data=d2a)
anova(lm2)
Anova(lm2,type="III")
summary(lm2)
```

### Evaluate Model Fit
The authors' Figure C shows the residuals *on the original maximum consumption scale* plotted against temperature.  The residuals are found by first creating predicted maximum consumptions by back-transforming fitted *log* maximum consumptions.  The differences between the observed maximum consumption and this predicted maximum consumption are the residuals plotted in Figure C.  The predictions and residual computations are below and then Figure C is constructed in parts largely as described for Figure A above.
```{r}
d2a$pCmax <- 10^lm2$fitted
d2a$resids2 <- d2a$Cmax-d2a$pCmax
plot(resids2~temp,data=d2a,type="n",xlab="Temperature",ylab="Residuals")
points(resids2~temp,data=d2a,subset=wtA=="38",col="red",pch=19)
points(resids2~temp,data=d2a,subset=wtA=="403",col="blue",pch=19)
points(resids2~temp,data=d2a,subset=wtA=="1567",col="black",pch=19)
abline(v=c(5,10,15,20,24,28),col="gray90",lty=3)
legend("topleft",legend=c("38 g","403 g","1567 g"),pch=19,col=c("red","blue","black"),
       lty=1,lwd=2)
```

The authors' Figure D was a bit more problematic to construct as they seemed to create "bands" of temperatures for which they summarized the predicted maximum consumptions.  They appeared to use different temperature "bands" for different sizes of fish.  I chose to create one set of "bands" that are illustrated by the faint gray lines in the plot above.  The "bands" were created with `recode()` (from the `car` package) rather than the multiple lines depicted for some of the variables above (e.g., `tempA`).  To do this, I created a new variable, called `tempB`, that contains the groupings for these "bands" and then computed the CV of the predicted maximum consumption for each weight grouping and temperature band using `ddply()`, from the `plyr` package.
```{r}
d2a$tempB <- recode(d2a$temp,"0:5='3'; 6:10='8'; 11:15='13'; 16:20='18'; 
                    21:23.5='22'; 24:28='26'; else='29'") 
sumcv <- ddply(d2a,c("wtA","tempB"),function(df) sd(df$pCmax)/mean(df$pCmax)*100)
names(sumcv)[3] <- "CV"
str(sumcv)
```

Figure D is then constructed in parts as shown below.
```{r}
plot(CV~tempB,data=sumcv,type="n",xlab="Temperature (C)",ylab="CV")
points(CV~tempB,data=sumcv,subset=wtA==38,type="b",pch=19,col="red",lwd=2)
points(CV~tempB,data=sumcv,subset=wtA==403,type="b",pch=19,col="blue",lwd=2)
points(CV~tempB,data=sumcv,subset=wtA==1567,type="b",pch=19,col="black",lwd=2)
legend("topright",legend=c("38 g","403 g","1567 g"),pch=19,col=c("red","blue","black"),
       lty=1,lwd=2)
```

This graph does not perfectly match Figure D because I used different "temperature bands."  However, it is functionally the same.

### Another Residual Plot
In my opinion it is important to look at the residual plot from the actual model fit (i.e., the residuals and fitted values from the log scale).  This plot cannot be constructed with `residPlot()`, from the `FSA` package.  Rather, the residuals and fitted values must be extracted from the `lm` object and plotted as shown below.  There does not appear to be a gross heteroscedasticity or non-linearity in this plot indicating that the assumptions of the linear model were approximately met on the scale to which the model was fit.  There does appear to be slightly more variability at the smaller fitted values and a possible outlier.
```{r}
plot(lm2$residuals~lm2$fitted,pch=19,xlab="Fitted Values",ylab="Residuals")
```

--------------------------------------------------------------

```{r echo=FALSE}
et <- proc.time() - stime
reproInfo(rqrdPkgs=rqrd,elapsed=et["user.self"]+et["sys.self"])
```

```{r echo=FALSE, results='hide', message=FALSE}
purl2("Chapter12.Rmd",moreItems=c("source","rqrd","stime"))    # Will create the script file
```

--------------------------------------------------------------
## References
